### ISSUE TITLE
Cross compilation on mac platform reports the following error

### ISSUE THREAD

**Issue by wangyulu** [erikdubbelboer/gspt#16]
$ GOOS=linux GOARCH=amd64 go build
go build github.com/erikdubbelboer/gspt: build constraints exclude all Go files in /Users/sky/Code/local/go/pkg/mod/github.com/erikdubbelboer/gspt@v0.0.0-20210805194459-ce36a5128377

**Comment by erikdubbelboer** [comment]
To cross compile gco code you have to specify `CGO_ENABLED=1` as well. So:
```sh
$ GOOS=linux GOARCH=amd64 CGO_ENABLED=1 go build
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
```
As you can see that will give you a bunch of header errors since the headers from Mac are different than for unix. So you'll need to somehow get all the correct linux headers and specify `CGO_CXXFLAGS="-I/path/to/headers`.

I have never done this before, I just know cross compiling cgo code can be a pain in the ass. You might be better off running Go in a Docker container and building from there.
